<?php

namespace models;


class Blog extends Entity
{
    private $id;
    public $DBUserFK;
    public $title;
    public $content;
    public $image="";

    protected function defaultValidationConfiguration()
    {

        $this->validator->isRequired('title');
        $this->validator->isRequired('content');
        $this->validator->maxLength('title',32);
        $this->validator->maxLength('content',4200);
    }

    public function seedSave(){
        $this->queryBuilder->setMode("insert")
            ->setIntoTable("DBBlog")
            ->setColumns(array("DBUserFK","Title","Content","Image"))
            ->addInsertValueSet(array($this->DBUserFK,$this->title,$this->content,$this->image))
            ->executeStatement();
    }
    public function update()
    {
        parent::update(); // TODO: Change the autogenerated stub
    }
    public function getAll(){
        return$this->queryBuilder->setMode("select")
            ->setColumns(array("DBBlog.ID","Title","Content","Image"))
            ->setFromTable("DBBlog")
            ->executeStatement();
    }
    public function save()
    {
        if($this->isValid()){
            $this->queryBuilder->setMode("insert")
                ->setIntoTable("DBBlog")
                ->setColumns(array("DBUserFK","Title","Content","Image"))
                ->addInsertValueSet(array($this->DBUserFK,$this->title,$this->content,$this->image))
                ->executeStatement();
        }else{
            echo"not valid";
        }
    }

}